image_processing_pipeline:
  video_file_path: "/home/emre/Downloads/YARGI.mp4"
  publish_frequency: 30
  filters:
    gaussian_blur:
      kernel_size: 40
    canny_edge_detection:
      low_threshold: 50.0
      high_threshold: 150.0
      enabled: true
    grayscale_conversion:
      enabled: false
